## Where the samples will be written
save_data: run/example
## Where the vocab(s) will be written
src_vocab: run/example.vocab.src
tgt_vocab: run/example.vocab.src
# Prevent overwriting existing files in the folder
overwrite: True

# Corpus opts:
data:
    corpus_1:
        path_src: data/data_subsample/src-train.txt
        path_tgt: data/data_subsample/tgt-train.txt
    valid:
        path_src: data/data_subsample/src-val.txt
        path_tgt: data/data_subsample/tgt-val.txt
share_vocab: 'true'
decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
rnn_size: 256
layers: 4
transformer_ff: 2048
heads: 8
dropout: 0.1

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'
share_embeddings: 'true'
global_attention: general
global_attention_function: softmax
self_attention_type: scaled-dot

batch_size: 6144
batch_type: tokens
normalization: tokens
label_smoothing: 0.0

max_generator_batches: 32


train_steps: 500000
accum_count: 4
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0
warmup_steps: 8000

save_model:  runs/checkpoints/data_subsample/data_subsample_model
save_checkpoint_steps: 10000
keep_checkpoint: 20
seed: 42
world_size: 4
gpu_ranks:
- 0
- 1
- 2
- 3